[[plugins]]
 package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "netlify-plugin-chromium"
inputs:
      setChromePathInEnv: false

 [[plugins]]
 package = "./netlify-scrapejobsplugin"