name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/5 * * * *' # every day at 14:00 denmark - 8:00 am Honduras
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f8d46b96663775fa711da96