# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Every 5 minutes
    - cron: '0 15 * * *'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f8d46b96663775fa711da96